{{- if not .Values.rudderWorkspaceTokenExistingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rudderstack.rudderWorkspaceTokenSecretName" . }}
  labels:
    {{- include "rudderstack.labels" . | nindent 4 }}
type: Opaque
data:
  rudderWorkspaceToken: {{ default "MISSING" .Values.rudderWorkspaceToken | b64enc | quote }}
{{- end }}

